# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)'


# System
[memory_usage]
disabled = true
threshold = -1
symbol = ' '
style = 'bold dimmed green'

# Battery
[battery]
disabled = false
[[battery.display]]
threshold = 20


# AWS
[aws]
format = 'on [$symbol$region]($style) '
style = 'bold blue'
symbol = 'ğŸ…° '
[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'
eu-west-1 = 'euw-1'
eu-west-2 = 'euw-2'

# Docker
[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

# Git
[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 16
truncation_symbol = ''
# ignore_branches = ['master', 'main']
[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'
[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

# Go
[golang]
format = 'via [ğŸğŸ’¨ $version](bold cyan) '

# Java
[java]
symbol = 'ğŸŒŸ '

# Python
[python]
symbol = 'ğŸ‘¾ '
pyenv_version_name = true

